name: Build Android APK
on:
push:
branches: [ master, main ]
workflow_dispatch: # Permite compilar manualmente
jobs:
build:
runs-on: ubuntu-latest
steps:
- name: Checkout code
uses: actions/checkout@v4
- name: Set up JDK 17
uses: actions/setup-java@v4
with:
java-version: '17'
distribution: 'temurin'
- name: Grant execute permission for gradlew
run: chmod +x gradlew
- name: Build Debug APK
run: ./gradlew assembleDebug
- name: Upload APK
uses: actions/upload-artifact@v4
with:
name: FloatingSwipeApp-Debug
path: app/build/outputs/apk/debug/app-debug.apk
